**Question:Python is a pretty versatile language. For which applications can you use Python?**

* You want to do some quick calculations.
* For your new business, you want to develop a database-driven website.
* Your boss asks you to clean and analyze the results of the latest satisfaction survey.
* All of the above.

_All of the above_

In [2]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball= np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [15]:
import pandas as pd
df=pd.read_csv('../datasets/baseball.csv', header=0)
height_in=np.array(df.values[:,3])
weight_lb=np.array(df.values[:,4])
print(height_in)

[74 74 72 ... 75 75 73]


In [16]:
# height is available as a regular list

# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in=np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
m=0.0254
np_height_m=np_height_in*m

# Print np_height_m
print(np_height_m)

[74 74 72 ... 75 75 73]
[1.8796 1.8796 1.8288 ... 1.905 1.905 1.8541999999999998]


In [17]:
# height and weight are available as regular lists

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg

np_weight_kg=np.array(weight_lb) * 0.453592
# Calculate the BMI: bmi
bmi=np_weight_kg/np_height_m**2

# Print out bmi
print(bmi)

[23.11037638875862 27.604060686572797 28.48080464679448 ...
 25.62295933480756 23.74810865177286 25.726863613607133]


In [18]:
# height and weight are available as regular lists

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg

np_weight_kg=np.array(weight_lb) * 0.453592
# Calculate the BMI: bmi
bmi=np_weight_kg/np_height_m**2

# Print out bmi
print(bmi)

[23.11037638875862 27.604060686572797 28.48080464679448 ...
 25.62295933480756 23.74810865177286 25.726863613607133]


In [19]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light=bmi<21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[bmi<21])

[False False False ... False False False]
[20.542556790007662 20.542556790007662 20.69282047151352 20.69282047151352
 20.343431890567484 20.343431890567484 20.69282047151352
 20.158834718074228 19.498447103560874 20.69282047151352 20.92052190452328]


In [20]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[50])

# Print out sub-array of np_height_in: index 100 up to and including index 110
np_height_in_sub=np_height_in[100:111]
print(np_height_in_sub)

200
[73 74 72 73 69 72 73 75 75 73 72]


# 2D Numpy Arrays

In [21]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball=np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [22]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball=np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


In [26]:
# baseball is available as a regular list of lists
# baseball = [[180, 78.4],
#            [215, 102.7],
#            [210, 98.5],
#            [188, 75.2]]
# Import numpy package
import numpy as np
baseball=list(df.values[:,[3,4]])
# Create np_baseball (2 cols)
np_baseball = np.array(baseball)
print(np_baseball.shape)
# Print out the 50th row of np_baseball
print(np_baseball[49])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb=np_baseball[:,1]
print(np_weight_lb)
# Print out height of 124th player
print(np_baseball[123,0])

(1015, 2)
[70 195]
[180 215 210 ... 205 190 195]
75


_update array is individiual for going on exercies _

In [43]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball =np.array( df.values[:,[3,4,5]])

print(np_baseball.shape)
updated=np_baseball*np.random.rand(0,1,3)
print(updated.shape)
# Print out addition of np_baseball and updated
print(np_baseball+updated)
# Create numpy array: conversion
conversion=np.array([0.0254, 0.453592,1])

# Print out product of np_baseball and conversion
result=np_baseball*conversion
print(result)

(1015, 3)
(0, 1015, 3)
[]
[[1.8796 81.64656 22.99]
 [1.8796 97.52228 34.69]
 [1.8288 95.25431999999999 30.78]
 ...
 [1.905 92.98636 25.19]
 [1.905 86.18248 31.01]
 [1.8541999999999998 88.45044 27.92]]


In [44]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height_in from np_baseball
np_height_in=np.array(np_baseball[:,0])

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

73.6896551724138
74.0


In [49]:
# np_baseball is available

# Import numpy
import numpy as np

np_baseball=np.array(np_baseball, dtype=float)
# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1]) 
print("Correlation: " + str(corr))

Average: 73.6896551724138
Median: 74.0
Standard Deviation: 2.312791881046546
Correlation: [[1.         0.53153932]
 [0.53153932 1.        ]]


* take positions and height from fifa.csv

In [54]:
import pandas as pd
df=pd.read_csv('../datasets/fifa.csv', header=0)
positions=(df.values[:,3])
heights=(df.values[:,4])

In [64]:
# heights and positions are available as lists

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions=np.char.strip(np.array(positions, dtype='str'))

# Heights of the goalkeepers: gk_heights
gk_heights=np_heights[np_positions=='GK']
print(gk_heights)
# Heights of the other players: other_heights
other_heights=np_heights[np_positions!='GK']
print(other_heights)
# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

[191 193 190 185 188 187 189 196 190 189 188 189 188 188 190 193 181 191
 193 190 183 183 193 193 196 184 190 186 195 191 187 185 186 185 186 190
 185 185 187 188 188 186 187 193 183 185 190 186 182 191 194 191 194 188
 185 189 187 188 184 176 187 186 191 188 191 192 190 188 189 184 180 191
 197 189 185 191 190 190 185 186 186 189 193 182 189 188 190 191 183 189
 189 190 188 184 194 188 194 193 186 186 188 187 191 192 196 187 187 187
 192 184 189 184 185 187 202 190 185 182 188 188 195 187 183 197 188 190
 193 191 187 184 183 185 193 180 191 185 188 188 186 188 188 184 186 189
 193 194 183 178 184 190 183 184 188 194 190 183 194 188 180 173 187 183
 184 193 188 183 190 191 199 186 198 188 189 189 185 193 191 188 185 185
 188 190 180 188 184 187 183 181 179 185 182 188 188 184 196 192 187 187
 193 190 189 194 188 185 193 185 193 187 196 194 198 196 188 188 195 186
 190 191 188 187 188 192 199 185 190 185 188 196 188 196 185 185 188 188
 179 187 190 185 198 193 193 188 188 180 183 185 18