# Neden NumPy?

In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

In [2]:
ab = []                        

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [3]:
import numpy as np

In [398]:
5*np.array([1, 2,3])

array([ 5, 10, 15])

In [5]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [6]:
a * b

array([ 2,  6, 12, 20])

# NumPy Array'i Oluşturmak

In [7]:
import numpy as np

In [8]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [9]:
a = np.array([1,2,3,4,5])

In [10]:
type(a)

numpy.ndarray

In [11]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [12]:
#sifirdan array olusturma 

In [13]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [16]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [17]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
np.random.normal(10, 4, (3,4))

array([[ 8.79299084,  8.84767396, 12.72471584, 13.31998911],
       [ 8.01997262, 22.81160551, 12.81870376, 13.59234282],
       [10.28456393, 17.50006605, 11.03817646, 10.13943966]])

In [19]:
np.random.randint(0,10, (3,3))

array([[1, 3, 0],
       [5, 8, 7],
       [6, 3, 4]])

# Özellikleri

* **ndim**: _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [20]:
import numpy as np

In [21]:
np.random.randint(10, size = 10)

array([8, 2, 4, 3, 0, 7, 5, 4, 5, 7])

In [22]:
a = np.random.randint(10, size = 10)

In [23]:
a.ndim

1

In [24]:
a.shape

(10,)

In [25]:
a.size

10

In [26]:
a.dtype

dtype('int32')

In [27]:
b = np.random.randint(10, size = (3,5))

In [28]:
b

array([[3, 4, 5, 2, 8],
       [7, 1, 6, 8, 6],
       [4, 3, 4, 9, 4]])

In [29]:
b.ndim

2

In [30]:
b.shape

(3, 5)

In [31]:
b.size

15

In [32]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme (Reshaping)

In [33]:
import numpy as np

In [34]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a = np.arange(1,10)

In [37]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a.ndim

1

In [39]:
b = a.reshape((1,9))

In [40]:
b.ndim

2

# Array Birlestirme (Concatenation)

In [41]:
import numpy as np

In [42]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [43]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [44]:
z = np.array([7,8,9])

In [45]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#iki boyut

In [47]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [48]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [50]:
import numpy as np

In [51]:
x = np.array([1,2,3,99,99,3,2,1])

In [52]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [53]:
a,b,c = np.split(x, [3,5])

In [54]:
a

array([1, 2, 3])

In [55]:
b

array([99, 99])

In [56]:
c

array([3, 2, 1])

In [57]:
#iki boyutlu ayırma

In [58]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [60]:
ust, alt = np.vsplit(m, [2])

In [61]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [65]:
sag, sol = np.hsplit(m, [2])

In [66]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [67]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [68]:
import numpy as np

In [69]:
v = np.array([2,1,4,3,5])

In [70]:
v

array([2, 1, 4, 3, 5])

In [71]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [72]:
v

array([2, 1, 4, 3, 5])

In [73]:
v.sort()

In [74]:
v

array([1, 2, 3, 4, 5])

In [75]:
#iki boyutlu array siralama

In [76]:
m = np.random.normal(20,5, (3,3))

In [77]:
m

array([[22.13322027, 20.554492  , 25.02309103],
       [18.59893576, 14.04987592, 13.15755512],
       [25.29942762, 26.12192854, 17.2212372 ]])

In [78]:
np.sort(m, axis = 1)

array([[20.554492  , 22.13322027, 25.02309103],
       [13.15755512, 14.04987592, 18.59893576],
       [17.2212372 , 25.29942762, 26.12192854]])

In [79]:
np.sort(m, axis = 0)

array([[18.59893576, 14.04987592, 13.15755512],
       [22.13322027, 20.554492  , 17.2212372 ],
       [25.29942762, 26.12192854, 25.02309103]])

# Index ile Elemanlara Erişmek

In [80]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([7, 4, 2, 4, 9, 8, 2, 8, 3, 6])

In [81]:
a[0]

7

In [82]:
a[-1]

6

In [83]:
a[0] = 100

In [84]:
a

array([100,   4,   2,   4,   9,   8,   2,   8,   3,   6])

In [85]:
m = np.random.randint(10, size = (3,5))
m

array([[2, 7, 7, 0, 1],
       [8, 3, 3, 1, 4],
       [6, 0, 4, 4, 8]])

In [86]:
m[0,0]

2

In [87]:
m[1,1]

3

In [88]:
m[1, 4]

4

In [89]:
m[1, 4] = 99

In [90]:
m

array([[ 2,  7,  7,  0,  1],
       [ 8,  3,  3,  1, 99],
       [ 6,  0,  4,  4,  8]])

In [91]:
m[1,4] = 2.2

In [92]:
m

array([[2, 7, 7, 0, 1],
       [8, 3, 3, 1, 2],
       [6, 0, 4, 4, 8]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [93]:
import numpy as np

In [94]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [95]:
a[0:3]

array([20, 21, 22])

In [96]:
a[:3]

array([20, 21, 22])

In [97]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [98]:
a[1::2]

array([21, 23, 25, 27, 29])

In [99]:
a[0::2]

array([20, 22, 24, 26, 28])

In [100]:
a[2::2]

array([22, 24, 26, 28])

In [101]:
a[0::3]

array([20, 23, 26, 29])

In [102]:
#iki boyutlu slice islemleri

In [103]:
m = np.random.randint(10, size = (5,5))

In [104]:
m

array([[4, 5, 3, 0, 0],
       [9, 3, 2, 8, 2],
       [9, 0, 1, 9, 5],
       [0, 0, 0, 2, 6],
       [2, 1, 4, 3, 9]])

In [105]:
m[:,0]

array([4, 9, 9, 0, 2])

In [106]:
m[:,1]

array([5, 3, 0, 0, 1])

In [107]:
m[:,4]

array([0, 2, 5, 6, 9])

In [108]:
m

array([[4, 5, 3, 0, 0],
       [9, 3, 2, 8, 2],
       [9, 0, 1, 9, 5],
       [0, 0, 0, 2, 6],
       [2, 1, 4, 3, 9]])

In [109]:
m[0,:]

array([4, 5, 3, 0, 0])

In [110]:
m[0]

array([4, 5, 3, 0, 0])

In [111]:
m[1,:]

array([9, 3, 2, 8, 2])

In [112]:
m[0:2, 0:3]

array([[4, 5, 3],
       [9, 3, 2]])

In [113]:
m[:,0:2]

array([[4, 5],
       [9, 3],
       [9, 0],
       [0, 0],
       [2, 1]])

In [114]:
m

array([[4, 5, 3, 0, 0],
       [9, 3, 2, 8, 2],
       [9, 0, 1, 9, 5],
       [0, 0, 0, 2, 6],
       [2, 1, 4, 3, 9]])

In [115]:
m[1:3, 0:2]

array([[9, 3],
       [9, 0]])

# Alt Küme Üzerinde İşlem Yapmak

In [116]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[4, 5, 5, 5, 8],
       [3, 5, 4, 2, 7],
       [3, 2, 1, 2, 9],
       [3, 0, 9, 0, 0],
       [2, 1, 4, 7, 8]])

In [117]:
alt_a = a[0:3, 0:2]
alt_a

array([[4, 5],
       [3, 5],
       [3, 2]])

In [118]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [119]:
alt_a

array([[99999,     5],
       [    3,   888],
       [    3,     2]])

In [120]:
a

array([[99999,     5,     5,     5,     8],
       [    3,   888,     4,     2,     7],
       [    3,     2,     1,     2,     9],
       [    3,     0,     9,     0,     0],
       [    2,     1,     4,     7,     8]])

In [121]:
m = np.random.randint(10, size = (5, 5))
m

array([[9, 4, 9, 0, 9],
       [1, 6, 4, 3, 0],
       [1, 1, 3, 9, 4],
       [0, 3, 2, 0, 0],
       [5, 6, 6, 4, 3]])

In [122]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[9, 4],
       [1, 6],
       [1, 1]])

In [123]:
alt_b[0,0] = 9999

In [124]:
alt_b

array([[9999,    4],
       [   1,    6],
       [   1,    1]])

In [125]:
m

array([[9, 4, 9, 0, 9],
       [1, 6, 4, 3, 0],
       [1, 1, 3, 9, 4],
       [0, 3, 2, 0, 0],
       [5, 6, 6, 4, 3]])

# Fancy Index ile Elemanlara Erişmek

In [126]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [127]:
v[1]

3

In [128]:
v[3]

9

In [129]:
v[5]

15

In [130]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [131]:
al_getir = [1,3,5]

In [132]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [133]:
v[al_getir]

array([ 3,  9, 15])

In [134]:
#iki boyutta fancy

In [135]:
m = np.arange(9).reshape((3,3))

In [136]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [137]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [138]:
m[satir, sutun]

array([1, 5])

In [139]:
#basit index ile fancy index

In [140]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [141]:
m[0, [1,2]]

array([1, 2])

In [142]:
#slice ile fancy

In [143]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [144]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [145]:
v < 3

array([ True,  True, False, False, False])

In [146]:
v[v < 3]

array([1, 2])

In [147]:
v[v > 3]

array([4, 5])

In [148]:
v[v >= 3]

array([3, 4, 5])

In [149]:
v[v <= 3]

array([1, 2, 3])

In [150]:
v[v == 3]

array([3])

In [151]:
v[v != 3]

array([1, 2, 4, 5])

In [152]:
v

array([1, 2, 3, 4, 5])

In [153]:
v * 2

array([ 2,  4,  6,  8, 10])

In [154]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [155]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [156]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

# Matematiksel İşlemler

In [157]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [158]:
v - 1

array([0, 1, 2, 3, 4])

In [159]:
v * 5

array([ 5, 10, 15, 20, 25])

In [160]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [161]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [162]:
#ufunc

In [163]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [164]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [165]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [166]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [167]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [168]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [169]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [170]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [171]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [172]:
np.absolute(np.array([-3]))

array([3])

In [173]:
np.sin(360)

0.9589157234143065

In [174]:
np.cos(180)

-0.5984600690578581

In [175]:
v = np.array([1,2,3])

In [176]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [177]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [178]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [179]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\tuba.demir2\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\tuba.demir2\appdata\local\programs\python\python38-32\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as

In [180]:
#cheatsheet

# İstatistiksel Hesaplamalar

In [181]:
v

array([1, 2, 3])

In [182]:
np.mean(v)

2.0

In [183]:
v.sum()

6

In [184]:
v.min()

1

* np.mean(arr,axis=0) | Returns mean along specific axis

* arr.sum() | Returns sum of arr

* arr.min() | Returns minimum value of arr

* arr.max(axis=0) | Returns maximum value of specific axis

* np.var(arr) | Returns the variance of array

* np.std(arr,axis=1) | Returns the standard deviation of specific axis

* arr.corrcoef() | Returns correlation coefficient of array

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [185]:
import numpy as np

**5 * x0 + x1 = 12  
x0 + 3 * x1 = 10**

In [186]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [187]:
a

array([[5, 1],
       [1, 3]])

In [188]:
b

array([12, 10])

In [189]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])

# BOLUM SONU DEGERLENDIRMESI

# Pandas Serisi Oluşturmak

In [190]:
import pandas as pd 

In [191]:
pd.Series([10,88,3,4,5])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [192]:
seri = pd.Series([10,88,3,4,5])

In [193]:
type(seri)

pandas.core.series.Series

In [194]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [195]:
seri.dtype

dtype('int64')

In [196]:
seri.size

5

In [197]:
seri.ndim

1

In [198]:
seri.values

array([10, 88,  3,  4,  5], dtype=int64)

In [199]:
seri.head(3)

0    10
1    88
2     3
dtype: int64

In [200]:
seri.tail(3)

2    3
3    4
4    5
dtype: int64

In [201]:
#index isimlendirmesi

In [202]:
pd.Series([99,22,332,94,5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [203]:
pd.Series([99,22,332,94,5], index = [1,3,5,7,9])

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [204]:
pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [205]:
seri = pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

In [206]:
seri["a"]

99

In [207]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

In [208]:
#sozluk uzerinden liste olusturmak

In [209]:
sozluk = {"reg":10, "log":11, "cart": 12}

In [210]:
seri = pd.Series(sozluk)

In [211]:
seri

reg     10
log     11
cart    12
dtype: int64

In [212]:
#iki seriyi birlestirerek seri olusturma

In [213]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

# Eleman İşlemleri

In [214]:
import numpy as np
a = np.array([1,2,33,444,75])
seri = pd.Series(a)
seri

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [215]:
seri[0]

1

In [216]:
seri[0:3]

0     1
1     2
2    33
dtype: int32

In [217]:
seri = pd.Series([121,200,150,99], 
                 index = ["reg","loj","cart","rf"])

In [218]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [219]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [220]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [221]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [222]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [223]:
#eleman sorgulama

In [224]:
"reg" in seri

True

In [225]:
"a" in seri

False

In [226]:
seri["reg"]

121

In [227]:
#fancy eleman

In [228]:
seri[["rf", "reg"]]

rf      99
reg    121
dtype: int64

In [229]:
seri["reg"] = 130

In [230]:
seri["reg"]

130

In [231]:
seri["reg":"loj"]

reg    130
loj    200
dtype: int64

# Pandas DataFrame Oluşturma

In [232]:
import pandas as pd

In [233]:
l = [1,2,39,67,90]

In [234]:
l

[1, 2, 39, 67, 90]

In [235]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [236]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [237]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [238]:
#df isimlendirme

In [239]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [240]:
df.columns = ("deg1","deg2","deg3")

In [241]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [242]:
type(df)

pandas.core.frame.DataFrame

In [243]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [244]:
df.shape

(3, 3)

In [245]:
df.ndim

2

In [246]:
df.size

9

In [247]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [248]:
type(df.values)

numpy.ndarray

In [249]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [250]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [251]:
a = np.array([1,2,3,4,5])

In [252]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

# Eleman İşlemleri

In [253]:
import numpy as np
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [254]:
sozluk = {"var1": s1, "var2": s2, "var3": s3}

In [255]:
sozluk

{'var1': array([5, 4, 9, 8, 5]),
 'var2': array([4, 6, 7, 7, 6]),
 'var3': array([1, 4, 3, 0, 2])}

In [256]:
df = pd.DataFrame(sozluk)

In [257]:
df

var1  var2  var3
0     5     4     1
1     4     6     4
2     9     7     3
3     8     7     0
4     5     6     2

In [258]:
df[0:1]

var1  var2  var3
0     5     4     1

In [259]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [260]:
df.index = ["a","b","c","d","e"]

In [261]:
df

var1  var2  var3
a     5     4     1
b     4     6     4
c     9     7     3
d     8     7     0
e     5     6     2

In [262]:
df["c":"e"]

var1  var2  var3
c     9     7     3
d     8     7     0
e     5     6     2

In [263]:
#silme

In [264]:
df.drop("a", axis = 0)

var1  var2  var3
b     4     6     4
c     9     7     3
d     8     7     0
e     5     6     2

In [265]:
df

var1  var2  var3
a     5     4     1
b     4     6     4
c     9     7     3
d     8     7     0
e     5     6     2

In [266]:
df.drop("a", axis = 0, inplace = True)

In [267]:
df

var1  var2  var3
b     4     6     4
c     9     7     3
d     8     7     0
e     5     6     2

In [268]:
#fancy 

In [269]:
l = ["c","e"]

In [270]:
df.drop(l, axis = 0)

var1  var2  var3
b     4     6     4
d     8     7     0

In [271]:
#degiskenler icin

In [272]:
df

var1  var2  var3
b     4     6     4
c     9     7     3
d     8     7     0
e     5     6     2

In [273]:
"var1" in df

True

In [274]:
l = ["var1","var4","var2"]

In [275]:
for i in l:
    print(i in df)

True
False
True


In [276]:
df

var1  var2  var3
b     4     6     4
c     9     7     3
d     8     7     0
e     5     6     2

In [277]:
df["var1"]

b    4
c    9
d    8
e    5
Name: var1, dtype: int32

In [278]:
df["var4"] = df["var1"] / df["var2"]

In [279]:
df

var1  var2  var3      var4
b     4     6     4  0.666667
c     9     7     3  1.285714
d     8     7     0  1.142857
e     5     6     2  0.833333

In [280]:
#degisken silmek

In [281]:
df.drop("var4", axis = 1)

var1  var2  var3
b     4     6     4
c     9     7     3
d     8     7     0
e     5     6     2

In [282]:
df

var1  var2  var3      var4
b     4     6     4  0.666667
c     9     7     3  1.285714
d     8     7     0  1.142857
e     5     6     2  0.833333

In [283]:
df.drop("var4", axis = 1, inplace = True)

In [284]:
df

var1  var2  var3
b     4     6     4
c     9     7     3
d     8     7     0
e     5     6     2

In [285]:
l = ["var1","var2"]

In [286]:
df.drop(l, axis = 1)

var3
b     4
c     3
d     0
e     2

# Gözlem ve Değişken Seçimi: loc & iloc

In [287]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    11    15    11
1    13    14    25
2    26    12     2
3     9    28    24
4    17    11    22
5    10     8    15
6     8    26    14
7    10    26     9
8    18    16     8
9     5     3    10

In [288]:
#loc: tanımlandığı şekli ile seçim yapmak için kullanılır.

In [289]:
df.loc[0:3]

var1  var2  var3
0    11    15    11
1    13    14    25
2    26    12     2
3     9    28    24

In [290]:
#iloc: alışık olduğumuz indeksleme mantığı ile seçim yapar.

In [291]:
df.iloc[0:3]

var1  var2  var3
0    11    15    11
1    13    14    25
2    26    12     2

In [292]:
df.iloc[0,0]

11

In [293]:
df

var1  var2  var3
0    11    15    11
1    13    14    25
2    26    12     2
3     9    28    24
4    17    11    22
5    10     8    15
6     8    26    14
7    10    26     9
8    18    16     8
9     5     3    10

In [294]:
df.iloc[:3,:2]

var1  var2
0    11    15
1    13    14
2    26    12

In [295]:
df.loc[0:3, "var3"]

0    11
1    25
2     2
3    24
Name: var3, dtype: int32

In [296]:
df.loc[0:3, "var3"]

0    11
1    25
2     2
3    24
Name: var3, dtype: int32

In [297]:
df.iloc[0:3]["var3"]

0    11
1    25
2     2
Name: var3, dtype: int32

# Koşullu Eleman İşlemleri

In [298]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    12    10    24
1     1    28     5
2    24     4    14
3     4    10     6
4    17     6    13
5     1    24    17
6    28     5    13
7     1    28     2
8    10    24    24
9    18    13    29

In [299]:
df["var1"]

0    12
1     1
2    24
3     4
4    17
5     1
6    28
7     1
8    10
9    18
Name: var1, dtype: int32

In [300]:
df[0:2][["var1","var2"]]

var1  var2
0    12    10
1     1    28

In [301]:
df

var1  var2  var3
0    12    10    24
1     1    28     5
2    24     4    14
3     4    10     6
4    17     6    13
5     1    24    17
6    28     5    13
7     1    28     2
8    10    24    24
9    18    13    29

In [302]:
df.var1

0    12
1     1
2    24
3     4
4    17
5     1
6    28
7     1
8    10
9    18
Name: var1, dtype: int32

In [303]:
df[df.var1 > 15]

var1  var2  var3
2    24     4    14
4    17     6    13
6    28     5    13
9    18    13    29

In [304]:
df[(df.var1 > 15) & (df.var3 < 5)]

Empty DataFrame
Columns: [var1, var2, var3]
Index: []

In [305]:
df.loc[(df.var1 > 15), ["var1","var2"]]

var1  var2
2    24     4
4    17     6
6    28     5
9    18    13

In [306]:
df[(df.var1 > 15)][["var1","var2"]]

var1  var2
2    24     4
4    17     6
6    28     5
9    18    13

# Birleştirme (Join) İşlemleri

In [307]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df1

var1  var2  var3
0    26     6     2
1     2    12     9
2     3    12     5
3     8     7    11
4    27    28    29

In [308]:
df2 = df1 + 99

In [309]:
df2

var1  var2  var3
0   125   105   101
1   101   111   108
2   102   111   104
3   107   106   110
4   126   127   128

In [310]:
pd.concat([df1,df2])

var1  var2  var3
0    26     6     2
1     2    12     9
2     3    12     5
3     8     7    11
4    27    28    29
0   125   105   101
1   101   111   108
2   102   111   104
3   107   106   110
4   126   127   128

In [311]:
?pd.concat

Signature:
pd.concat(
    objs: Union[Iterable[~FrameOrSeries], Mapping[Union[Hashable, NoneType], ~FrameOrSeries]],
    axis=0,
    join='outer',
    ignore_index: bool = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: bool = False,
    sort: bool = False,
    copy: bool = True,
) -> Union[ForwardRef('DataFrame'), ForwardRef('Series')]
Docstring:
Concatenate pandas objects along a particular axis with optional set logic
along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raise

In [312]:
pd.concat([df1,df2], ignore_index=True)

var1  var2  var3
0    26     6     2
1     2    12     9
2     3    12     5
3     8     7    11
4    27    28    29
5   125   105   101
6   101   111   108
7   102   111   104
8   107   106   110
9   126   127   128

In [313]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [314]:
df2.columns = ["var1","var2","deg3"]

In [315]:
df2

var1  var2  deg3
0   125   105   101
1   101   111   108
2   102   111   104
3   107   106   110
4   126   127   128

In [316]:
df1

var1  var2  var3
0    26     6     2
1     2    12     9
2     3    12     5
3     8     7    11
4    27    28    29

In [317]:
pd.concat([df1, df2])

var1  var2  var3   deg3
0    26     6   2.0    NaN
1     2    12   9.0    NaN
2     3    12   5.0    NaN
3     8     7  11.0    NaN
4    27    28  29.0    NaN
0   125   105   NaN  101.0
1   101   111   NaN  108.0
2   102   111   NaN  104.0
3   107   106   NaN  110.0
4   126   127   NaN  128.0

In [318]:
pd.concat([df1, df2], join = "inner")

var1  var2
0    26     6
1     2    12
2     3    12
3     8     7
4    27    28
0   125   105
1   101   111
2   102   111
3   107   106
4   126   127

In [319]:
pd.concat([df1, df2], join_axes = [df2.columns], ignore_index=True)

TypeError: concat() got an unexpected keyword argument 'join_axes'

# İleri Birleştirme İşlemleri

In [320]:
import pandas as pd

In [321]:
#birebir birlestirme

In [322]:
df1 = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'İK']})

df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [323]:
df2 = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],
                    'ilk_giris': [2010, 2009, 2014, 2019]})

df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [324]:
pd.merge(df1, df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [325]:
pd.merge(df1, df2, on = "calisanlar")

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [326]:
#coktan teke 

In [327]:
df3 = pd.merge(df1, df2)

In [328]:
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [329]:
df4 = pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'İK'],
                    'mudur': ['Caner', 'Mustafa', 'Berkcan']})

df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [330]:
pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [331]:
# çoktan çoka

In [332]:
df5 = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                              'Muhendislik', 'Muhendislik', 'İK', 'İK'],
                    'yetenekler': ['matematik', 'excel', 'kodlama', 'linux',
                               'excel', 'yonetim']})

df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [333]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [334]:
pd.merge(df1, df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           İK      excel
7      Fatma           İK    yonetim

# Toplulaştırma ve Gruplama (Aggregation & Grouping)

Basit toplulaştırma fonksiyonları:

* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [335]:
import seaborn as sns

In [336]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [337]:
df = sns.load_dataset("planets")
df.head()

HTTPError: HTTP Error 503: Service Unavailable

In [338]:
df.shape

(10, 3)

In [339]:
df.mean()

var1    11.6
var2    15.2
var3    14.7
dtype: float64

In [340]:
df["mass"].mean()

KeyError: 'mass'

In [341]:
df["mass"].count()

KeyError: 'mass'

In [342]:
df["mass"].min()

KeyError: 'mass'

In [343]:
df["mass"].max()

KeyError: 'mass'

In [344]:
df["mass"].sum()

KeyError: 'mass'

In [345]:
df["mass"].std()

KeyError: 'mass'

In [346]:
df["mass"].var()

KeyError: 'mass'

In [347]:
df.describe().T

count  mean       std  min   25%   50%    75%   max
var1   10.0  11.6  9.946524  1.0  1.75  11.0  17.75  28.0
var2   10.0  15.2  9.750214  4.0  7.00  11.5  24.00  28.0
var3   10.0  14.7  8.944893  2.0  7.75  13.5  22.25  29.0

In [348]:
df.dropna().describe().T

count  mean       std  min   25%   50%    75%   max
var1   10.0  11.6  9.946524  1.0  1.75  11.0  17.75  28.0
var2   10.0  15.2  9.750214  4.0  7.00  11.5  24.00  28.0
var3   10.0  14.7  8.944893  2.0  7.75  13.5  22.25  29.0

# Gruplama İşlemleri

In [349]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'veri': [10,11,52,23,43,55]}, columns=['gruplar', 'veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [350]:
df.groupby("gruplar")

In [351]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [352]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [353]:
df = sns.load_dataset("planets")
df.head()

HTTPError: HTTP Error 503: Service Unavailable

In [354]:
df.groupby("method")

KeyError: 'method'

In [355]:
df.groupby("method")["orbital_period"].mean()

KeyError: 'method'

In [356]:
df.groupby("method")["orbital_period"].describe()

KeyError: 'method'

# İleri Toplulaştırma İşlemleri (Aggregate, filter, transform, apply)

In [357]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [358]:
#aggregate

In [359]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A               16        181
B               17        182
C               66        651

In [360]:
df.groupby("gruplar").aggregate([min, np.median, max])

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10     16  22       100    181  262
B              11     17  23       111    182  253
C              33     66  99       333    651  969

In [361]:
df.groupby("gruplar").aggregate({"degisken1": "min", "degisken2": "max"})

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

In [362]:
#filter

In [363]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [364]:
def filter_func(x):
    return x["degisken1"].std() > 9

In [365]:
df.groupby("gruplar").std()

degisken1   degisken2
gruplar                       
A         8.485281  114.551299
B         8.485281  100.409163
C        46.669048  449.719913

In [366]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

In [367]:
#transform

In [368]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [369]:
df["degisken1"]*9

0     90
1    207
2    297
3    198
4     99
5    891
Name: degisken1, dtype: int64

In [370]:
df_a = df.iloc[:,1:3]

In [371]:
df_a.transform(lambda x: (x-x.mean()) / x.std())

degisken1  degisken2
0  -0.687871  -0.738461
1  -0.299074  -0.263736
2   0.000000  -0.015514
3  -0.328982  -0.235811
4  -0.657963  -0.704331
5   1.973890   1.957853

In [372]:
#apply

In [373]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [374]:
df.apply(np.sum)

gruplar      ABCABC
degisken1       198
degisken2      2028
dtype: object

In [375]:
df.apply(np.mean)

TypeError: Could not convert ABCABC to numeric

In [376]:
df.groupby("gruplar").apply(np.mean)

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

# Pivot Tablolar

In [377]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

HTTPError: HTTP Error 503: Service Unavailable

In [378]:
titanic.groupby("sex")[["survived"]].mean()

NameError: name 'titanic' is not defined

In [379]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

NameError: name 'titanic' is not defined

In [380]:
#pivot ile table

In [381]:
titanic.pivot_table("survived", index = "sex", columns = "class")

NameError: name 'titanic' is not defined

In [382]:
titanic.age.head()

NameError: name 'titanic' is not defined

In [383]:
age = pd.cut(titanic["age"], [0, 18, 90])
age.head(10)

NameError: name 'titanic' is not defined

In [384]:
titanic.pivot_table("survived", ["sex", age], "class")

NameError: name 'titanic' is not defined

# Dış Kaynaklı Veri Okumak

In [385]:
import pandas as pd

In [386]:
?pd.read_csv

Signature:
pd.read_csv(
    filepath_or_buffer: Union[str, pathlib.Path, IO[~AnyStr]],
    sep=',',
    delimiter=None,
    header='infer',
    names=None,
    index_col=None,
    usecols=None,
    squeeze=False,
    prefix=None,
    mangle_dupe_cols=True,
    dtype=None,
    engine=None,
    converters=None,
    true_values=None,
    false_values=None,
    skipinitialspace=False,
    skiprows=None,
    skipfooter=0,
    nrows=None,
    na_values=None,
    keep_default_na=True,
    na_filter=True,
    verbose=False,
    skip_blank_lines=True,
    parse_dates=False,
    infer_datetime_format=False,
    keep_date_col=False,
    date_parser=None,
    dayfirst=False,
    cache_dates=True,
    iterator=False,
    chunksize=None,
    compression='infer',
    thousands=None,
    decimal: str = '.',
    lineterminator=None,
    quotechar='"',
    quoting=0,
    doublequote=True,
    escapechar=None,
    comment=None,
    encoding=None,
    dialect=None,
    error_bad_lines=True,
    warn_bad_l

In [387]:
#csv okuma
pd.read_csv("reading_data/ornekcsv.csv", sep = ";")

FileNotFoundError: [Errno 2] No such file or directory: 'reading_data/ornekcsv.csv'

In [388]:
#txt okuma
pd.read_csv("reading_data/duz_metin.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'reading_data/duz_metin.txt'

In [389]:
#excel
pd.read_excel("reading_data/ornekx.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'reading_data/ornekx.xlsx'

In [390]:
df = pd.read_excel("reading_data/ornekx.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'reading_data/ornekx.xlsx'

In [391]:
type(df)

pandas.core.frame.DataFrame

In [392]:
df.head()

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111

In [393]:
df.columns = ("A","B","C")

In [394]:
df

A   B    C
0  A  10  100
1  B  23  253
2  C  33  333
3  A  22  262
4  B  11  111
5  C  99  969

In [395]:
#sıfırdan txt okuma
tips = pd.read_csv("reading_data/data.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'reading_data/data.txt'

In [396]:
tips.head()

NameError: name 'tips' is not defined

# Bonus: Problem Çözme ve Döküman Okuma Kültürü

In [397]:
9 / 0

ZeroDivisionError: division by zero

# BOLUM SONU DEGERLENDIRMESI